BINARY     = servo_usb
OBJS      += multi_servo.o usb_cdcacm.o blink.o ../../libs/microrl/microrl.o command_line.o control_context.o ../../libs/utils.o pwm_timer_servo.o softpwm_servo.o

LDSCRIPT = ../stm32-f103.ld

include ../libopencm3.stm32f1.mk
