BINARY     = servo_usb
OBJS      += ../servo_pwm/pwm.o multi_servo.o usb_cdcacm.o blink.o ../../libs/microrl/microrl.o command_line.o control_context.o ../../libs/utils.o

LDSCRIPT = ../stm32-f103.ld

include ../libopencm3.stm32f1.mk
